- lib/parlour/rbi_generator/rbi_object.rb
- spec/rbi_generator_spec.rb
Input:
```ruby
create_module('M') do |m|
m.add_comment(['This is a', 'multi-line', 'comment'])
end
```
Output:
```ruby
module M
end
```
It also aliases `add_comment` to `add_comments`.
> Add support for multi-line comments

- lib/parlour/conflict_resolver.rb
- lib/parlour/plugin.rb
- lib/parlour/rbi_generator.rb
- lib/parlour/rbi_generator/attribute.rb
- lib/parlour/rbi_generator/class_namespace.rb
- lib/parlour/rbi_generator/method.rb
- lib/parlour/rbi_generator/module_namespace.rb
- lib/parlour/rbi_generator/namespace.rb
- lib/parlour/rbi_generator/options.rb
- lib/parlour/rbi_generator/parameter.rb
- lib/parlour/rbi_generator/rbi_object.rb
I know this is repetitive of the Sorbet types, but if the documentation is going to be generated with YARD it should use these.
> Add YARD types to all parameters and return tags.

- lib/parlour/rbi_generator/namespace.rb
- spec/rbi_generator_spec.rb
Input:
```ruby
@parlour.root.create_class(name: 'Foo') do |foo|
foo.create_extends(['X', 'Y', 'Z'])
foo.create_includes(['A', 'B', 'C'])
end
```
Output:
```ruby
class Foo
include A
include B
include C
extend X
extend Y
extend Z
end
```
Resolves #23.
> Add create_includes and create_extends methods.

- lib/parlour/rbi_generator/namespace.rb
I think the old example was copied from create_include without modification
> Update example for create_constant

- lib/parlour/rbi_generator/namespace.rb
Instead of using `T.must` and marking them as nilable, I'm pretty sure not specifying a default value does the same thing without needing any Sorbet-specific code.
I may be missing some reason not to do it this way :)
> Make method parameters required

- lib/parlour/plugin.rb
Sometimes the syntax below isn't accepted
```
plugins.each do |plugin|
rescue
end
```
See error below:
```
[dev@ip-10-0-0-61 v5.2 (model_rbi_plugins *)]$ bundle exec rake rails_rbi:models
rake aborted!
SyntaxError: /home/dev/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/parlour-0.5.1/lib/parlour/plugin.rb:42: syntax error, unexpected keyword_rescue, expecting keyword_end
rescue Exception => e
^
/home/dev/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/parlour-0.5.1/lib/parlour/plugin.rb:59: syntax error, unexpected keyword_end, expecting end-of-input
```
That syntax is only a feature of Ruby 2.5
https://blog.bigbinary.com/2017/10/24/ruby-2.5-allows-rescue-inside-do-end-blocks.html
> Wrap rescue in a begin-end

- README.md
- lib/parlour/rbi_generator/attribute.rb
- lib/parlour/rbi_generator/namespace.rb
- lib/parlour/rbi_generator/parameter.rb
- lib/parlour/rbi_generator/rbi_object.rb
- plugin_examples/foobar_plugin.rb
- spec/conflict_resolver_spec.rb
- spec/parameter_spec.rb
- spec/rbi_generator_spec.rb
This changes all methods which took a `name:` keyword argument to accept it as their first and only positional argument instead. (Fix #28.)
@connorshea / @manhhung741 - a quick review and/or your comments would be greatly appreciated!
> Change "name" to a positional argument

- .travis.yml
- lib/parlour.rb
- lib/parlour/kernel_hack.rb
- lib/parlour/plugin.rb
- lib/parlour/rbi_generator/namespace.rb
I'd like to be able to use Parlour with more versions of Ruby. This change will run spec against different version of Ruby. It might fail on ruby v2.3 and v2.4. We'll fix it before merging this change.
> Test against more versions of Ruby

- exe/parlour
- lib/parlour/plugin.rb
- lib/parlour/rbi_generator.rb
- spec/rbi_generator_spec.rb
The `RbiGenerator#rbi` method now takes an optional strictness. Plugins can request a particular strictness, and the weakest strictness requested will be used for the entire RBI file.
Closes #21.
@connorshea / @manhhung741 - quick review would be greatly appreciated!
_(As an aside, why can't I use GitHub's "request reviewers" feature? Nobody appears in the list, even if I type usernames exactly...)_
> Implement strictness preference

- .travis.yml
Builds and deploys documentation only once while testing on many Ruby versions.
> Change docs into build stage

- lib/parlour/conflict_resolver.rb
- lib/parlour/rbi_generator/attribute.rb
- lib/parlour/rbi_generator/method.rb
- lib/parlour/rbi_generator/namespace.rb
- spec/conflict_resolver_spec.rb
- spec/rbi_generator_spec.rb
This adds support for attributes wrapped in a `class << self` block, which closes #42.
(Also, my Git name was _still_ `=` - I think it's sorted now...)
This touches quite a few files, so review would be appreciated!
> Add class attributes

- lib/parlour/rbi_generator/method.rb
- lib/parlour/rbi_generator/namespace.rb
- spec/rbi_generator_spec.rb
This implements support for type parameters in methods, using the `type_parameters` modifier in a `sig` before `params`.
Closes #41.
> Implement type parameter support

- lib/parlour/rbi_generator/method.rb
On my Rails app it takes 2m4s to run `bundle exec rake rails_rbi:all` with typechecking enabled for `Parlour::RbiGenerator::Method#==`, and 1m4s without it. The reason I noticed this problem is because I added a bunch of metaprogramming-created methods to sorbet-rails, and it started to become annoyingly slow.
This is because once you add enough methods to a module/class, the number of comparisons that occurs grows (I think?) exponentially.
This makes Parlour spend a lot of time in the resolve conflicts stage. Based on profiling the rake task, there were >8.6 million calls to `Method#==`. Once you get to that many calls, I guess typechecking the method becomes a performance bottleneck.
See the docs for `checked`: https://sorbet.org/docs/runtime#checked-whether-to-check-in-the-first-place …
> Disable typechecking for `Method#==` to improve performance.

- lib/parlour/conflict_resolver.rb
This removes a layer of complexity in the special case that all of the conflicting objects are exactly equal. If they are, then one `Array#delete` will clear them all out.
This means there's no need to iterate over each child and delete it, since the first delete will remove all children and subsequent deletes will do nothing but take time.
> Optimise by handling all_eql? early and with lower complexity

- parlour.gemspec
The distributed exe/parlour requires the commander gem, but it is not listed in your gemspec. This means simply adding parlour to your `Gemfile` is insufficient to use the gem.
This PR adds the current minor version as a dependency.
> Adding missing depdency of Commander

- README.md
- exe/parlour
- sorbet/rbi/hidden-definitions/errors.txt
- sorbet/rbi/hidden-definitions/hidden.rbi
The plugin I'm working on needs all the models included for reflection, this PR allows for the use of [glob patters](https://ruby-doc.org/core-2.6.5/Dir.html#method-c-glob) in relative requires
I found no specs for the CLI, so this PR lacks and specs for this functionality.
> Allow globs in relative require

- lib/parlour/rbi_generator.rb
- lib/parlour/rbi_generator/namespace.rb
- lib/parlour/rbi_generator/options.rb
- lib/parlour/rbi_generator/parameter.rb
- sorbet/rbi/hidden-definitions/hidden.rbi
- spec/rbi_generator_spec.rb
- spec/spec_helper.rb
This adds a `sort_namespaces` option to the `Options` class and `RbiGenerator` constructor.
When true, this sorts the children of all namespaces alphabetically, though it preserves the existing grouping of `include` and `extend` calls. Arbitrary objects are also kept above all other normal objects, as their name is blank.
When false, the ordering remains the same as it was before this PR.
Closes #59.
> Add "sort namespaces" option

- lib/parlour/rbi_generator/namespace.rb
- lib/parlour/type_parser.rb
- spec/type_loader_spec.rb
Resolves https://github.com/AaronC81/parlour/issues/65
I also fixed a failing test by forcing the children sorting to be stable (preserve order for equivalent sort items). It's less efficient, but that shouldn't matter since nodes don't tend to have a lot of children.
Also sorry about the whitespace noise. My editor was removing trailing whitespace, but I can get rid of those changes if it's annoying.
> Handle undeclared block args

- lib/parlour/type_parser.rb
- spec/type_parser_spec.rb
Fixes #69 
I created a new method based on `parse_sig_into_methods` called `parse_method_into_methods`. This new method will generate `RbiGenerator::Method`s and `RbiGenerator::Attribute`s from unsigged methods, setting any parameter types and return types to `T.untyped`. 
I had started by trying to adapt the `parse_sig_into_methods` to handle the `sig` not being present but there were a lot of validations sprinkled throughout the method and adding a bunch of conditionals made it much harder to read. One idea on how to remove some of the duplication:
- Leave the `parse_method_into_methods` as-is, basically take a method call or `attr_*` and return a method/attribute that is totally untyped.
- Have the `parse_sig_into_methods`
- Parse the sig
- Call the `parse_method_into_methods` to …
> Parse methods without sigs

- lib/parlour/type_parser.rb
- spec/type_parser_spec.rb
Fixes an issue I bumped into loading some structs in our codebase that only had a single prop.
> Fix parsing struct with a single node

- lib/parlour/type_parser.rb
- spec/type_parser_spec.rb
Trying out the new struct parsing code in my project (thanks - very useful!) and hit a crash when parsing a struct property that was a `T::Boolean` with a default value of `false`. The code in TypeParser that constructed StructProp instances would always cast :true, :false, or :sym AST nodes to their actual value, instead of preserving them as Strings of ruby code, as expected by the `default` constructor arg to StructProp.
Included test repros the issue (as well as testing some other corner cases), and the patch makes the test pass, though I'm open for suggestions on improving the fix if you think there's a cleaner way to do the value node handling.
> Struct default values should always be Strings of ruby code

- lib/parlour/type_parser.rb
- spec/type_parser_spec.rb
I had set the `return_value` to `nil` when loading methods without signatures which I realized means `void`. The return value for these should be `T.untyped`.
> When loading methods without sigs set return to T.untyped

- lib/parlour/conflict_resolver.rb
- spec/conflict_resolver_spec.rb
This works by special-casing the conflict resolver's naming.
Closes #79.
> Fix conflict between writers and methods of the same name

- lib/parlour/conflict_resolver.rb
- lib/parlour/rbi_generator/enum_class_namespace.rb
- lib/parlour/rbi_generator/struct_class_namespace.rb
- lib/parlour/type_parser.rb
- spec/conflict_resolver_spec.rb
Fixes #78 
~Want to confirm this works on my codebase with no regressions.~ Confirmed 🙂 
Fixing conflict resolution in specialized namespaces (i.e. Enum and Struct). Some notable changes:
- Handle merging a plain `ClassNamespace` with one of the specialized ones
- Handle merging multiple of the same specialized namespaces if they have the either the same enums/props (or some are empty).
- When merging multiple specialized namespaces choose the non-empty enums/props.
- Fix issue where load order of plain `ClassNamespace` vs the specialized ones would affect mergeability (i.e. say things were mergeable when they shouldn't be).
Wanted to call out the last commit which specifically orders the namespaces when using the `differing_namespaces` strategy. I found cases where a module namespace was …
> Fix specialized classes conflict resolver

- .parlour
- README.md
- exe/parlour
- lib/parlour/detached_rbi_generator.rb
- lib/parlour/plugin.rb
- lib/parlour/rbi_generator/parameter.rb
- lib/parlour/type_loader.rb
- lib/parlour/type_parser.rb
- rbi/parlour.rbi
- spec/conflict_resolver_spec.rb
- spec/type_loader_spec.rb
- spec/type_parser_spec.rb
Sets up Parlour to easily generate gem RBI. This basically pulls in the functionality provided by `brain_freeze` so you can just do everything with `parlour` instead of needing an additional gem.
Some changes:
- Previously the parlour CLI was set up to only run plugins. Now it first run the `TypeLoader.load_project`, then the plugins, and run the conflict resolver on the result.
- The `TypeParser` would previously use the `DetachedRbiGenerator` throughout but now it will default to using that but also accept an `RbiGenerator` that you can pass in. This lets us reuse the same generator/root for both the `load_project` and the plugins.
- Add options:
- `root`: defaults to `'.'`, should usually be your project root, should be where your `sorbet` folder lives.
- `included_paths`: Lets you …
> Make it easier to generate gem RBI

- lib/parlour/rbi_generator/constant.rb
- lib/parlour/rbi_generator/namespace.rb
- rbi/parlour.rbi
- spec/rbi_generator_spec.rb
Closes #90.
This adds the ability for constants to be defined on eigenclasses by creating them with the `eigen_constant` keyword argument set to `true.
> Add support for generating constants on eigenclasses

- lib/parlour/conflict_resolver.rb
The block passed to `resolve_conflicts` is allowed to return `nil`. Most of the caller code handles this correctly by doing stuff like
```ruby
choice = resolver.call("Different kinds of definition for the same name", children)
namespace.children << choice if choice
```
And the docs allow this:
It's just the sig that's wrong. Note that the bundled `parlour.rbi` will need to be regenerated too.
Came across this while working on https://github.com/chanzuckerberg/sorbet-rails/pull/367
> Fix incorrect sig

- lib/parlour/type_parser.rb
- lib/parlour/types.rb
- rbi/parlour.rbi
- spec/type_parser_spec.rb
- spec/types_spec.rb
Related sord issue: https://github.com/AaronC81/sord/issues/121
This commit adds
- Parlour::Types::Generic, which represents a generic class with an
arbitrary number of type parameters
- support for Parlour::Types::Generic to Parlour::TypeParser
I considered was using `Generic` to implement some of the built in generics like `Hash`, `Array` etc. It feels a natural thing to do, but we'd need to add some sort of `Raw`-like type that handles the `T::Hash` vs `::Hash` vs `Hash` stuff.
> Support user-defined generic classes.

- lib/parlour/types.rb
- spec/types_spec.rb
`generate_rbi` was outputting `T::::Array`. Should `describe` also return root level types? I was following how Hash is implemented, which just has `Hash<Key, Value>`
> Fix SingleElementCollection types.

- lib/parlour/rbi_generator/class_namespace.rb
- lib/parlour/rbi_generator/enum_class_namespace.rb
- lib/parlour/rbi_generator/module_namespace.rb
- lib/parlour/rbi_generator/namespace.rb
- lib/parlour/rbi_generator/struct_class_namespace.rb
- lib/parlour/type_parser.rb
- rbi/parlour.rbi
- spec/rbi_generator_spec.rb
- spec/type_parser_spec.rb
Adds support for generating and parsing `sealed!` on classes and modules in RBI.
Closes #106.
> Add "sealed!" generation and parsing support

- lib/parlour/rbi_generator/namespace.rb
- rbi/parlour.rbi
- spec/rbi_generator_spec.rb
There were a few things wrong with the way the current code was looking up constant names:
1. The parameter supplied to the `path` method can be typed as a `Module` since `Class` is a subclass of `Module`, thus, every constant would be a `Module`.
2. The parameter name as `object` was misleading, since we don't expect any random object, but a constant.
3. Looking up the name of a constant via the `to_s` method is a world of pain, since `to_s` does more magic like converting singleton names to `#<Class:Foo>` format or refinement names to `#<refinement:Bar xxx>` format. All of these are ultimately useless as a class/module identifier and cannot be processed properly by this method. We should be looking up the actual `name` of the constant.
4. Looking up the actual name of the constant is …
> Improve constant name lookup

- lib/parlour/rbi_generator/namespace.rb
- spec/rbi_generator_spec.rb
As promised in #112, here is a small patch that streamlines and improves constant type matching in the `path` method.
Here are the highlights of the changes:
1. Instead of looping over the name parts twice, we are now iterating over the parts once and collecting them in a `namespace` array as we keep descending. That removes the need to pass temporary values around between the two loops as well.
2. In order to detect the type of the constant at each level, we are now essentially using `Class === instance` instead of looking up `instance.class`, which could be overridden. Encapsulating the check in a `case/when` construct makes that much more streamlined.
3. We do fallback to reading the `class` of the instance only if the type is not `Module` or `Class`, which we only use for error …
> Improve constant type matching

- parlour.gemspec
Excludes the `rbi` directory when building the gem, hopefully fixing #101.
> Do not bundle RBI with built gem

- lib/parlour/typed_object.rb
I was having some problems with a SorbetRails plugin where the conflict resolution stage was taking an obscenely long time. This makes that problem significantly less severe.
For my open source Rails app vglist, it consistently decreases the time spent generating type signatures down from 14 seconds to 9 seconds. For a large Rails app, the difference is _much_ more significant. From 750 seconds down to 314 seconds.
I can't share more specific info from the larger app (proprietary and all that), but I can share the flamegraphs for my personal project [vglist](https://github.com/connorshea/vglist): https://gist.github.com/connorshea/a6e8c303b8464af90f33b98278fd3276
Unfortunately GitHub Gists don't allow JS inside an SVG to be run (even if you open them as Raw), so if you want to look at …
> Disable typechecking on the name attribute for TypedObject.

- lib/parlour.rb
- lib/parlour/mixin/searchable.rb
- lib/parlour/rbi_generator/class_namespace.rb
- lib/parlour/rbi_generator/enum_class_namespace.rb
- lib/parlour/rbi_generator/module_namespace.rb
- lib/parlour/rbi_generator/namespace.rb
- lib/parlour/rbi_generator/struct_class_namespace.rb
- lib/parlour/rbs_generator/class_namespace.rb
- lib/parlour/rbs_generator/interface_namespace.rb
- lib/parlour/rbs_generator/module_namespace.rb
- lib/parlour/rbs_generator/namespace.rb
- rbi/parlour.rbi
- sorbet/config
- spec/rbi_generator_spec.rb
- spec/rbs_generator_spec.rb
This adds two new methods to `Namespace` for RBI and RBS, using a new `Searchable` mixin - `#find` and `#find_all`, for returning the first child or all children of a namespace respectively, based on a set of criteria.
The `name:` keyword argument can be used to filter by the name of the child, and `type:` can be used to filter by its class.
I did consider just implementing `Enumerable`, but decided against it since a `Namespace` does a bit more than just hold its children - it may contain modifiers such as `final!` or `interface!`, and also has quite a few methods for code generation. If you do want to use it like an `Enumerable`, it's already easy enough to do so using `#children` to grab the underlying array.
Closes #73.
> Add #find and #find_all for RBI/RBS Namespace

- lib/parlour/debugging.rb
Resolves some warnings when invoking `yard doc`. This makes the repo warning-free when invoking yard with the `yard-sorbet` plugin (this repo doesn't use the plugin, but it's still useful for me to test against it).
> Fix YARD warnings

- lib/parlour/type_parser.rb
- spec/type_parser_spec.rb
I ran into an interesting issue today when Sorbet tried to typecheck some Parlour-generated code from one of my gems:
```
sorbet/rbi/gems/kube-dsl@0.7.1.rbi:10950: The initialize method should always return void https://srb.help/3510
10950 |  sig { returns(T.untyped) }
^^^^^^^^^^^^^^^^^^
Autocorrect: Use `-a` to autocorrect
sorbet/rbi/gems/kube-dsl@0.7.1.rbi:10950: Replace with void
10950 |  sig { returns(T.untyped) }
```
The `#initialize` method is somewhat special in that its return value is always discarded, and in a recent release it looks like the Sorbet folks have decided to enforce void return values for all `#initialize` instance methods.
> #initialize methods should always return void

- lib/parlour/mixin/searchable.rb
- rbi/parlour.rbi
Fixes type check failure which started recently; presumably due to a Sorbet change making this more strict:
```
./lib/parlour/mixin/searchable.rb:49: Call to method `name` on unbounded type member `Parlour::Mixin::Searchable::Child` https://srb.help/7039
49 |        (name.nil? ? true : child.name == name) \
^^^^
Got `Parlour::Mixin::Searchable::Child` originating from:
./lib/parlour/mixin/searchable.rb:48:
48 |      def searchable_child_matches(child, name, type)
^^^^^
Consider adding an `upper` bound to `Parlour::Mixin::Searchable::Child` here
./lib/parlour/mixin/searchable.rb:11:
11 |      Child = type_member
^^^^^^^^^^^^^^^^^^^
./lib/parlour/mixin/searchable.rb:[5](https://github.com/AaronC81/parlour/runs/6342620404?check_suite_focus=true#step:5:5)0: Call to method `is_a?` on unbounded …
```
> Add upper bound to Searchable::Child

- .github/workflows/ruby.yml
- exe/parlour
`File#exists?` has now been removed, so use `exist?`
> Fix Parlour CLI on Ruby 3.2.0

- lib/parlour/rbi_generator/attribute.rb
- lib/parlour/rbi_generator/class_namespace.rb
- lib/parlour/rbi_generator/enum_class_namespace.rb
- lib/parlour/rbi_generator/module_namespace.rb
- lib/parlour/rbi_generator/struct_class_namespace.rb
- lib/parlour/rbs_generator/attribute.rb
- lib/parlour/rbs_generator/class_namespace.rb
Fixes type checking failures introduced by `--typed-super` becoming the default: sorbet/sorbet@db48e97
I tried just disabling `--typed-super`, but we support Ruby versions (2.4-2.6) whose newest Sorbet versions don't have this option
> Cast initialiser blocks to more abstract `T.proc` types

- lib/parlour/types.rb
- spec/types_spec.rb
Sorbet does not support a no-argument form of Proc.params(); current code generates RBI which fails in 'srb tc' with:
```
<filename>:<line>: params must be given arguments https://srb.help/5003
<line> |  sig { params(task_name: String, block: T.proc.params().returns(Object)).returns(Object) }
```
> Don't generate Proc.params() when Proc takes no parameters

- lib/parlour/rbi_generator/constant.rb
- lib/parlour/rbi_generator/namespace.rb
- lib/parlour/type_parser.rb
- rbi/parlour.rbi
- spec/rbi_generator_spec.rb
- spec/type_parser_spec.rb
Fixes invalid heredoc bodies which were generated in .rbi files because the body of them was not generated.
RBI generated before - Sorbet scans to the end of the file to find the 'HEREDOC' tag, doesn't find it, emits an error and ignores the rest of the .rbi file.
```
FOO = T.let(<<~HEREDOC, String)
```
After:
```
FOO = T.let(<<~HEREDOC, String)
foo
HEREDOC
```
> Generate heredoc bodies in constants

- lib/parlour/plugin.rb
- lib/parlour/rbi_generator/rbi_object.rb
- lib/parlour/rbs_generator/rbs_object.rb
- lib/parlour/typed_object.rb
Tapioca now converts some RBS directives into Sorbet directives, including `@abstract`, which happens to match YARD's syntax.
Unfortunatley this clashes with the `abstract!` directive, and gives an error that we've duplicated it.
This is very convenient, but I think Sorbet's comment syntax is still experimental - so I'd rather remove this than the classic `abstract!` directive.
(This documentation mostly appears on classes/methods that a Parlour user won't be interacting with, anyway.)
Closes #147.
> Remove YARD `@abstract` directives

- lib/parlour/type_loader.rb
I found this in a larger project; Open3.popen3 requires either threaded or select() based reading to avoid one full buffer on an output stream blocking the process continuing to execute while you wait for input on another sttream.
Open3.capture3() handles all of this for you if you don't mind not streaming the read.
> Fix I/O deadlock issue
